import { Component } from '@angular/core';
import { MatecuAutocompleteMultiple } from '../../../../projects/angular-matecu/src/lib/components/matecu-autocomplete-multiple/matecu-autocomplete-multiple';
import { MatFormFieldModule } from '@angular/material/form-field';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-autocomplete-multiple',
  imports: [
    MatecuAutocompleteMultiple,
    MatFormFieldModule,
    ReactiveFormsModule,
    CommonModule,
    MatIconModule,
  ],
  templateUrl: './autocomplete-multiple.html',
  styleUrls: ['./autocomplete-multiple.scss'],
})
export class AutocompleteMultiple {
  control = new FormControl<string[]>([]);
  countries: [string, string][] = [
    ['hola', 'Hola Mundo el pueblo unido jamás será vencido ni el prd ni el pan'],
    ['cn', 'China'],
    ['us', 'United States'],
    ['jp', 'Japan'],
    ['de', 'Germany'],
    ['fr', 'France'],
    ['gb', 'United Kingdom'],
    ['it', 'Italy'],
    ['ca', 'Canada'],
    ['au', 'Australia'],
    ['br', 'Brazil'],
    ['ru', 'Russia'],
    ['in', 'India'],
    ['es', 'Spain'],
    ['mx', 'Mexico'],
    ['kr', 'South Korea'],
    ['sa', 'Saudi Arabia'],
    ['za', 'South Africa'],
    ['tr', 'Turkey'],
    ['ir', 'Iran'],
    ['id', 'Indonesia'],
    ['ch', 'Switzerland'],
    ['se', 'Sweden'],
    ['nl', 'Netherlands'],
    ['be', 'Belgium'],
    ['ar', 'Argentina'],
    ['no', 'Norway'],
    ['pl', 'Poland'],
    ['th', 'Thailand'],
    ['eg', 'Egypt'],
    ['gr', 'Greece'],
    ['pt', 'Portugal'],
    ['fi', 'Finland'],
    ['dk', 'Denmark'],
    ['hu', 'Hungary'],
    ['cz', 'Czech Republic'],
    ['ro', 'Romania'],
    ['ve', 'Venezuela'],
    ['cl', 'Chile'],
    ['nz', 'New Zealand'],
    ['ua', 'Ukraine'],
    ['my', 'Malaysia'],
    ['sg', 'Singapore'],
    ['ph', 'Philippines'],
    ['vn', 'Vietnam'],
    ['co', 'Colombia'],
    ['pe', 'Peru'],
    ['bd', 'Bangladesh'],
    ['ng', 'Nigeria'],
    ['ke', 'Kenya'],
    ['dz', 'Algeria'],
    ['ma', 'Morocco'],
    ['gh', 'Ghana'],
    ['qa', 'Qatar'],
    ['kw', 'Kuwait'],
    ['om', 'Oman'],
    ['bh', 'Bahrain'],
    ['lb', 'Lebanon'],
    ['jo', 'Jordan'],
    ['sy', 'Syria'],
    ['ye', 'Yemen'],
    ['af', 'Afghanistan'],
    ['np', 'Nepal'],
    ['lk', 'Sri Lanka'],
    ['mm', 'Myanmar'],
    ['kh', 'Cambodia'],
    ['la', 'Laos'],
    ['bt', 'Bhutan'],
    ['mv', 'Maldives'],
    ['bn', 'Brunei'],
    ['tl', 'Timor-Leste'],
    ['cy', 'Cyprus'],
    ['is', 'Iceland'],
    ['lu', 'Luxembourg'],
    ['li', 'Liechtenstein'],
    ['mc', 'Monaco'],
    ['sm', 'San Marino'],
    ['va', 'Vatican City'],
  ];
}
